name: Notion 2 GitHub Pages

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

jobs:
  notion_to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notion to GitHub
        uses: raymondcamden/notion-to-github-action@main
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
